---
apiVersion: v1
kind: Service
metadata:
  name: web-iad-federated
  annotations:
    federation.tigera.io/serviceSelector:
      app == "web-iad"
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: web-pdx
  labels:
    app: web-pdx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: web-pdx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-pdx
spec:
  selector:
    matchLabels:
      app: web-pdx
  serviceName: "web-pdx"
  replicas: 1
  template:
    metadata:
      labels:
        app: web-pdx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate

